//
// Created by Moolet on 29/03/2021.
//

#ifndef TEENSY_EURORACK_TEENSY_EURORACK_PINS_H
#define TEENSY_EURORACK_TEENSY_EURORACK_PINS_H

#define TEENSY_EURORACK_PIN_ENC1_SW     4
#define TEENSY_EURORACK_PIN_ENC1_A      12
#define TEENSY_EURORACK_PIN_ENC1_B      24

#define TEENSY_EURORACK_PIN_ENC2_SW     9
#define TEENSY_EURORACK_PIN_ENC2_A      25
#define TEENSY_EURORACK_PIN_ENC2_B      28

#define TEENSY_EURORACK_PIN_ENC3_SW     10
#define TEENSY_EURORACK_PIN_ENC3_A      29
#define TEENSY_EURORACK_PIN_ENC3_B      30

#define TEENSY_EURORACK_PIN_POT1        14
#define TEENSY_EURORACK_PIN_POT2        15
#define TEENSY_EURORACK_PIN_POT3        41
#define TEENSY_EURORACK_PIN_POT4        22

#endif //TEENSY_EURORACK_TEENSY_EURORACK_PINS_H
